"""
Database Management Module (database.py)
Handles SQLite database initialization, user authentication, password hashing,
and patient report persistence for users and system administrators.
"""

import sqlite3
import os
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from utils.logger import logger

DB_PATH = "neurocare.db"

def get_db_connection():
    """Establishes and returns a database connection with dict-like row access."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    """Initializes database tables and creates default admin account if not existing."""
    conn = get_db_connection()
    cursor = conn.cursor()

    # 1. Users Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT DEFAULT 'user',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # 2. Reports Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS reports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER,
            patient_name TEXT NOT NULL,
            age INTEGER,
            gender TEXT,
            diagnosis TEXT NOT NULL,
            final_probability_pct REAL NOT NULL,
            risk_level TEXT NOT NULL,
            confidence_score REAL NOT NULL,
            cognitive_prob REAL NOT NULL,
            eeg_prob REAL NOT NULL,
            speech_prob REAL NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users (id)
        )
    ''')

    conn.commit()

    # 3. Seed Default Admin Account if missing
    cursor.execute("SELECT * FROM users WHERE username = ?", ("admin",))
    if not cursor.fetchone():
        admin_pass = generate_password_hash("admin123")
        cursor.execute(
            "INSERT INTO users (username, email, password_hash, role) VALUES (?, ?, ?, ?)",
            ("admin", "admin@neurocare.ai", admin_pass, "admin")
        )
        conn.commit()
        logger.info("Default Admin account created: username='admin', password='admin123'")

    conn.close()
    logger.info("Database initialized successfully.")

def register_user(username, email, password, role='user'):
    """Registers a new user account."""
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        pass_hash = generate_password_hash(password)
        cursor.execute(
            "INSERT INTO users (username, email, password_hash, role) VALUES (?, ?, ?, ?)",
            (username, email, pass_hash, role)
        )
        conn.commit()
        user_id = cursor.lastrowid
        conn.close()
        return True, user_id
    except sqlite3.IntegrityError:
        conn.close()
        return False, "Username or Email already exists."
    except Exception as e:
        conn.close()
        return False, str(e)

def authenticate_user(username_or_email, password):
    """Authenticates user or admin credentials."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT * FROM users WHERE username = ? OR email = ?",
        (username_or_email, username_or_email)
    )
    user = cursor.fetchone()
    conn.close()

    if user and check_password_hash(user['password_hash'], password):
        return dict(user)
    return None

def save_patient_report(user_id, patient_name, age, gender, report_dict):
    """Saves a generated patient report into the database."""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    ind = report_dict.get('individual_probabilities', {})
    
    cursor.execute('''
        INSERT INTO reports (
            user_id, patient_name, age, gender, diagnosis,
            final_probability_pct, risk_level, confidence_score,
            cognitive_prob, eeg_prob, speech_prob
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ''', (
        user_id,
        patient_name,
        int(age),
        gender,
        report_dict.get('diagnosis', 'Healthy / Control Baseline'),
        float(report_dict.get('final_probability_pct', 0.0)),
        report_dict.get('risk_level', 'Low'),
        float(report_dict.get('confidence_score', 90.0)),
        float(ind.get('cognitive', 0.0)),
        float(ind.get('eeg', 0.0)),
        float(ind.get('speech', 0.0))
    ))
    conn.commit()
    report_id = cursor.lastrowid
    conn.close()
    return report_id

def get_user_reports(user_id):
    """Retrieves all past patient reports generated by a specific user."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT * FROM reports WHERE user_id = ? ORDER BY created_at DESC",
        (user_id,)
    )
    reports = [dict(r) for r in cursor.fetchall()]
    conn.close()
    return reports

def get_all_reports_admin():
    """Retrieves all patient reports across the entire system for Admin view."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('''
        SELECT r.*, u.username as account_username, u.email as account_email
        FROM reports r
        LEFT JOIN users u ON r.user_id = u.id
        ORDER BY r.created_at DESC
    ''')
    reports = [dict(r) for r in cursor.fetchall()]
    conn.close()
    return reports

def get_admin_stats():
    """Returns summary statistics for the Admin Dashboard."""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    cursor.execute("SELECT COUNT(*) as total_users FROM users WHERE role = 'user'")
    total_users = cursor.fetchone()['total_users']
    
    cursor.execute("SELECT COUNT(*) as total_reports FROM reports")
    total_reports = cursor.fetchone()['total_reports']
    
    cursor.execute("SELECT COUNT(*) as high_risk FROM reports WHERE risk_level = 'High'")
    high_risk = cursor.fetchone()['high_risk']

    cursor.execute("SELECT COUNT(*) as healthy FROM reports WHERE risk_level = 'Low'")
    healthy = cursor.fetchone()['healthy']
    
    conn.close()
    return {
        'total_users': total_users,
        'total_reports': total_reports,
        'high_risk': high_risk,
        'healthy': healthy
    }
