services:
  - type: web
    name: alzheimer-prediction-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python prod_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
